from re import I
from turtle import st


features = {
    'unnamed':                  'Unnamed: 0',
    'flow_id':                  'Flow ID',
    'source_ip':                ' Source IP',
    'source_port':              ' Source Port',
    'destination_ip':           ' Destination IP',
    'destination_port':         ' Destination Port',
    'protocol':                 ' Protocol',
    'timestamp':                ' Timestamp',
    'flow_duration':            ' Flow Duration',
    'total_fwd_packets':        ' Total Fwd Packets',
    'total_bwd_packets':        ' Total Backward Packets',
    'total_len_fwd_packets':    'Total Length of Fwd Packets',
    'total_len_bwd_packets':    ' Total Length of Bwd Packets',
    'fwd_packet_len_max':       ' Fwd Packet Length Max',
    'fwd_packet_len_min':       ' Fwd Packet Length Min',
    'fwd_packet_len_mean':      ' Fwd Packet Length Mean',
    'fwd_packat_len_std':       ' Fwd Packet Length Std',
    'bwd_packet_len_max':       'Bwd Packet Length Max',
    'bwd_packet_len_min':       ' Bwd Packet Length Min',
    'bwd_packet_len_mean':      ' Bwd Packet Length Mean',
    'bwd_packet_len_std':       ' Bwd Packet Length Std',
    'flow_bytes_s':             'Flow Bytes/s',
    'flow_packets_s':           ' Flow Packets/s',
    'flow_iat_mean':            ' Flow IAT Mean',
    'flow_iat_std':             ' Flow IAT Std',
    'flow_iat_max':             ' Flow IAT Max',
    'flow_iat_min':             ' Flow IAT Min',
    'fwd_iat_total':            'Fwd IAT Total',
    'fwd_iat_mean':             ' Fwd IAT Mean',
    'fwd_iat_std':              ' Fwd IAT Std',
    'fwd_iat_max':              ' Fwd IAT Max',
    'fwd_iat_mean':             ' Fwd IAT Min',
    'bwd_iat_total':            'Bwd IAT Total',
    'bwd_iat_mean':             ' Bwd IAT Mean',
    'bwd_iat_std':              ' Bwd IAT Std',
    'bwd_iat_max':              ' Bwd IAT Max',
    'bwd_iat_min':              ' Bwd IAT Min',
    'fwd_psh_flags':            'Fwd PSH Flags',
    'bwd_psh_flags':            ' Bwd PSH Flags',
    'fwd_urg_flags':            ' Fwd URG Flags',
    'bwd_urg_flags':            ' Bwd URG Flags',
    'fwd_header_len':           ' Fwd Header Length',
    'bwd_header_len':           ' Bwd Header Length',
    'fwd_packets_s':            'Fwd Packets/s',
    'bwd_packets_s':            ' Bwd Packets/s',
    'min_packet_len':           ' Min Packet Length',
    'max_packet_len':           ' Max Packet Length',
    'packet_len_min':           ' Packet Length Mean',
    'packet_len_std':           ' Packet Length Std',
    'packet_len_variance':      ' Packet Length Variance',
    'fin_flag_count':           'FIN Flag Count',
    'syn_flag_count':           ' SYN Flag Count',
    'rst_flag_count':           ' RST Flag Count',
    'psh_flag_count':           ' PSH Flag Count',
    'ack_flag_count':           ' ACK Flag Count',
    'urg_flag_count':           ' URG Flag Count',
    'cwe_flag_count':           ' CWE Flag Count',
    'ece_flag_count':           ' ECE Flag Count',
    'down_up_ratio':            ' Down/Up Ratio',
    'avg_packet_size':          ' Average Packet Size',
    'avg_fwd_seg_size':         ' Avg Fwd Segment Size',
    'avg_bwd_seg_size':         ' Avg Bwd Segment Size',
    'fwd_header_len1':          ' Fwd Header Length.1',
    'fwd_avg_bytes_bulk':       'Fwd Avg Bytes/Bulk',
    'fwd_avg_packets_bulk':     ' Fwd Avg Packets/Bulk',
    'fwd_avg_bulk_rate':        ' Fwd Avg Bulk Rate',
    'bwd_avg_bytes_bulk':       ' Bwd Avg Bytes/Bulk',
    'bwd_avg_packets_bulk':     ' Bwd Avg Packets/Bulk',
    'bwd_avg_bulk_rate':        'Bwd Avg Bulk Rate',
    'subflow_fwd_packets':      'Subflow Fwd Packets',
    'subflow_fwd_bytes':        ' Subflow Fwd Bytes',
    'subflow_bwd_packets':      ' Subflow Bwd Packets',
    'subflow_bwd_bytes':        ' Subflow Bwd Bytes',
    'init_win_bytes_fwd':       'Init_Win_bytes_forward',
    'init_win_bytes_bwd':       ' Init_Win_bytes_backward',
    'act_data_pkt_fwd':         ' act_data_pkt_fwd',
    'min_seg_size_fwd':         ' min_seg_size_forward',
    'active_mean':              'Active Mean',
    'active_std':               ' Active Std',
    'active_max':               ' Active Max',
    'active_min':               ' Active Min',
    'idle_mean':                'Idle Mean',
    'idle_std':                 ' Idle Std',
    'idle_max':                 ' Idle Max',
    'idle_min':                 ' Idle Min',
    'similar_http':             'SimillarHTTP',
    'inbound':                  ' Inbound',
    'label':                    ' Label'
}
